# Generated by Django 5.1.7 on 2025-03-29 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='admin_signup',
            name='username',
            field=models.CharField(default='default_username', max_length=100),
        ),
    ]
