# Generated by Django 4.2.7 on 2025-03-24 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0002_signup'),
    ]

    operations = [
        migrations.AddField(
            model_name='signup',
            name='is_superuser',
            field=models.BooleanField(default=False),
        ),
    ]
