# Generated by Django 5.1.7 on 2025-03-29 09:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0002_admin_signup_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='admin_signup',
            name='username',
        ),
    ]
