# Generated by Django 5.1.7 on 2025-03-29 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0003_remove_admin_signup_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='admin_signup',
            name='username',
            field=models.CharField(default='default_username', max_length=100, unique=True),
        ),
    ]
