# Generated by Django 5.1.7 on 2025-03-29 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0004_admin_signup_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admin_signup',
            name='username',
            field=models.CharField(db_collation='utf8_bin', default='zoro', max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='signup',
            name='username',
            field=models.CharField(db_collation='utf8_bin', default='zoro', max_length=100),
        ),
    ]
